name: auto-merge

on:
  pull_request:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          github-token: ${{ secrets.mytoken }}
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '15.x'
      - run: npm ci
      - run: npm install
      - run: npm run build --if-present
